version: "3.9"

name: hp

services:
  svc1:
    image: dextercdalogdog/hello-world-service:dev-lts-cc2a19019fb40abfb003a40bbd130529504b8c0a
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000"
    environment:
      SERVICE_NAME: "svc1"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "job=service1"

  svc2:
    image: dextercdalogdog/hello-world-service:dev-lts-cc2a19019fb40abfb003a40bbd130529504b8c0a
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000"
    environment:
      SERVICE_NAME: "svc2"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "job=service2"

  svc3:
    image: dextercdalogdog/hello-world-service:dev-lts-cc2a19019fb40abfb003a40bbd130529504b8c0a
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000"
    environment:
      SERVICE_NAME: "svc3"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "job=service3"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - svc1
      - svc2
      - svc3
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "job=nginx"

  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki/data:/data/loki
    command: -config.file=/etc/loki/loki-config.yaml

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - loki

  promtail:
    container_name: promtail
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail/config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki